### PR TITLE
Updated Warp secondary parameters to go from 9 to 11, in corresponden…

### PR DESCRIPTION
**Pull request by MajorCooke**
…ce  with the upcoming pitch + radius offset additions.

(Also, I had absolutely no way to prevent the git crushing file change. I changed one number, and it blows up. No idea what to do about that.)

### CODE REVIEW

**Comment by Blzut3** [comment]
When this happens it means your text editor is changing the line endings.  Usually because the file has mixed line endings (because someone else's text editor isn't smart enough to be consistent).  Switch between unix and windows line ending modes and one of them should have far fewer changes.

**Comment by MajorCooke** [comment]
I don't think that's possible with notepad unfortunately... That's all I used to open it.

**Comment by Blzut3** [comment]
Yeah don't use notepad for code editing.  If you need a simple editor I recommend replacing notepad with notepad2 which has proper support for line endings.

**Comment by Gaerzi** [comment]
Yeah there are at least three notepad replacements that are all leagues better than notepad:
[notepad2](http://www.flos-freeware.ch/notepad2.html)
[notepad++](https://notepad-plus-plus.org/)
[pnotepad](http://www.pnotepad.org/)

For fuck's sake, never use notepad. Never. It messes whitespace, randomly inserts new lines in order to word wrap in the current window size, screws up character encoding, and a lot of other unforgivable sins.

Never use notepad.

**Comment by MajorCooke** [comment]
Gaerzi: Chill out please.

Blzut3: Okay. I'll just redo this by editing using github directly.

**Pull request closed without merging**
