### PR TITLE
New Eternity functions: GetLineCenterX and GetLineCenterY

### PR DESCRIPTION
**Pull request by ioan-chera**
Added due to demand. They return a linedef's centre point coordinates. Useful for example when the linedef is moving (e.g. by polyobjects).

### CODE REVIEW

**Comment by Gaerzi** [comment]
Rather than returning the center, something like this might make more sense:

GetLinePosX(LINE_START): X pos of v1
GetLinePosX(LINE_STOP): X pos of v2
and optionally: GetLinePosX(LINE_CENTER): X pos of middle

Then same for GetLinePosY.

Why? Because that way you can generalize things such as spawning glass shards along a breakable window (without having to place map spots for that like in Hexen). You can compute the length of the line, check its angle, etc.

**Comment by ioan-chera** [comment]
Sounds better, yes. I may have to add constants to defs though. Wait till I update it, then.

**Comment by coelckers** [comment]
What's up with this? You told us to wait but nothing has happened in 4 weeks. Is this still active?

**Comment by ioan-chera** [comment]
Whoops. I totally forgot about this. No problem though, it's easy to add it, it doesn't depend on portal heavy work. Just wait for me to add them tonight in Eternity (even though I *hate* spending time verifying/testing ACS).

**Comment by ioan-chera** [comment]
Hello, I've updated the specifications to be satisfactory now. Here they are: GetLineX and GetLineY.
Arguments: (int line_id, fixed line_ratio, fixed perpendicular_distance).

Line ratio is normally from 0 to 1, which means the relative position from v1 to v2 where to get the coordinate (0.5 means middle).

Perpendicular distance is the distance (in map units) away from the linedef, in front of it (if positive).

No constants needed to be added.

**Pull request merged**
